services:
  ejercicio-dotnet-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ejercicio-dotnet-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "TuContrasena123*"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/bin/bash -lc 'echo > /dev/tcp/127.0.0.1/1433'"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 20s
    restart: no

  ejercicio-dotnet-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ejercicio-dotnet-backend
    depends_on:
      ejercicio-dotnet-db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      # Avoid redirection to HTTPS within the container
      DisableHttpsRedirect: "true"
      ConnectionStrings__DefaultConnection: "Server=ejercicio-dotnet-db,1433;Database=sample;User Id=sa;Password=TuContrasena123*;Encrypt=True;TrustServerCertificate=True"
    ports:
      - "8080:8080"
    restart: no

volumes:
  mssql-data:
